# Generated by Django 3.2.10 on 2021-12-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100)),
                ('t_icon', models.CharField(max_length=500)),
                ('t_player_count', models.IntegerField()),
                ('t_top_bat', models.CharField(max_length=500)),
                ('t_top_bowl', models.CharField(max_length=500)),
                ('t_won_count', models.IntegerField()),
            ],
        ),
    ]
