# Generated by Django 3.2.10 on 2021-12-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='t_icon',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_player_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_top_bat',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_top_bowl',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_won_count',
            field=models.IntegerField(null=True),
        ),
    ]
