# Generated by Django 3.2.10 on 2021-12-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0003_auto_20211209_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='t_icon',
            field=models.FileField(null=True, upload_to='media/t_icon/'),
        ),
    ]
