# Generated by Django 3.2.10 on 2021-12-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0004_alter_team_t_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='t_icon',
            field=models.FileField(null=True, upload_to='media/ticon/'),
        ),
    ]
