# Generated by Django 3.2.10 on 2021-12-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0005_alter_team_t_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=100, null=True)),
                ('p_photo', models.FileField(null=True, upload_to='media/photo/')),
                ('p_team', models.CharField(blank=True, max_length=500, null=True)),
                ('p_price', models.CharField(blank=True, max_length=500, null=True)),
                ('p_play_status', models.CharField(blank=True, max_length=500, null=True)),
                ('t_role', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
