# Generated by Django 3.2.10 on 2021-12-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0007_auto_20211213_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='p_photo',
            field=models.FileField(null=True, upload_to='media/photo/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='t_icon',
            field=models.FileField(null=True, upload_to='media/ticon/'),
        ),
    ]
